name: Feature Request
description: Suggest a new feature or enhancement for Alchemix AWDL
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - xAlcahest
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a new feature! Describe what you'd like to see added to Alchemix AWDL.

  - type: textarea
    id: description
    attributes:
      label: What feature would you like?
      description: Describe the feature you'd like to see
      placeholder: |
        Example: "Add support for downloading multiple anime simultaneously..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature is this?
      options:
        - Download functionality
        - User interface / UX
        - Configuration / Settings
        - Performance improvement
        - Search / Discovery
        - Episode management
        - Network / Connection handling
        - Database / Tracking
        - Logging / Debugging
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details, examples, or references
      placeholder: "Examples, similar features in other tools, etc..."

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
