name: Site Support Request
description: Request support for a new anime streaming site
title: "[SITE] "
labels: ["site-support"]
assignees:
  - xAlcahest
body:
  - type: markdown
    attributes:
      value: |
        ## Site Support Request

        Request support for a new anime streaming site to be added to Alchemix AWDL.

  - type: input
    id: site-name
    attributes:
      label: Site Name
      description: Name of the anime streaming site
      placeholder: "Example: AnimeWorld.to"
    validations:
      required: true

  - type: input
    id: site-url
    attributes:
      label: Site URL
      description: Main URL of the site
      placeholder: "https://www.example.com"
    validations:
      required: true

  - type: dropdown
    id: site-type
    attributes:
      label: Site Type
      description: What type of site is this?
      options:
        - Streaming site (similar to current AnimeWorld)
        - Direct download site
        - Torrent tracker
        - Other
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why should this site be supported?
      description: Explain why this site would be useful
      placeholder: |
        Example: "This site has a larger catalog of anime and better video quality..."
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      label: Site Region/Language
      description: What region or language is this site primarily for?
      options:
        - Italian
        - English
        - Multi-language
        - Other
    validations:
      required: true

  - type: textarea
    id: technical-info
    attributes:
      label: Technical Information (if known)
      description: Any technical details about the site structure
      placeholder: |
        - Video hosting service used (e.g., Voe, Streamtape)
        - Direct download links available: Yes/No
        - Requires authentication: Yes/No
        - Other relevant details...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information
      placeholder: "Similar sites, comparison with AnimeWorld.ac, etc..."

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: The site is legal and publicly accessible
          required: true
